title: "Mamen  Portfolio"
description: "Mi portafolio profesional"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
show_downloads: true
sass:
  sass_dir: _sass
  style: compressed
